### ISSUE TITLE
Request: pyodbc

### ISSUE THREAD

**Issue by aeorxc** [keithrozario/Klayers#105]
Hi

Please could you kindly add pyodbc to your collection?

**Comment by keithrozario** [comment]
Apologies, at the moment we can't support packages that require a c-compiler to compile :(

pyodbc has wheels for macOS and Windows, but not Amazon Linux, which is what lambda runs on.

**Comment by childnick** [comment]
@keithrozario I assume this is the same for exchangelib (which relies on lxml)?

**Comment by keithrozario** [comment]
I'll check this out later, might not be an issue.

**Comment by keithrozario** [comment]
@childnick exchangelib turned out to not require this.

You can use via the layer here:
arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-exchangelib:1

swap the region for whichever you want to use :)

**Comment by childnick** [comment]
You're a legend, thank you so much!
