### ISSUE TITLE
[FEATURE] Add support for chevron

### ISSUE THREAD

**Issue by richmidwinter** [keithrozario/Klayers#108]
Any chance you could add support for chevron (or alternative mustache templating library)? Thanks.

**Comment by keithrozario** [comment]
Done.
e.g. 
**arn:aws:lambda:ap-southeast-1:770693421928:layer:Klayers-python38-chevron:1**

To get the latest layer version for a region, query the api:

- https://api.klayers.cloud/api/v1/layers/latest/ap-southeast-1/chevron
- https://api.klayers.cloud/api/v1/layers/latest/us-east-1/chevron
