### ISSUE TITLE
Request: Spanish SpaCy models

### ISSUE THREAD

**Issue by adriaanbd** [keithrozario/Klayers#109]
** Additional Packages**:
Could you please provide an ARN for Spanish SpaCy [models](https://spacy.io/models/es#es_core_news_md)? Thank you!

**Comment by keithrozario** [comment]
Do you have the link to download the Spanish model?

**Comment by adriaanbd** [comment]
Thanks for taking it into consideration! All of the links are here: https://github.com/explosion/spacy-models/releases//tag/es_core_news_sm-2.3.1. The small model is okay for now but ofcourse a medium one would be nice to have. The url can be structured like this (I'm sure you have this already just thought I'd share):

```
model = 'es_core_news_sm-2.3.1'
url = f'https://github.com/explosion/spacy-models/releases/download/{model}/{model}.tar.gz'
```

For our immediate purpose, the download link for the tar gz file is [here](https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-2.3.1/es_core_news_sm-2.3.1.tar.gz).

**Comment by keithrozario** [comment]
ok, give me 1-2 weeks. Will try over this weekend :)

**Comment by keithrozario** [comment]
Included this today:
arn:aws:lambda:\<*region*>:770693421928:layer:Klayers-python38-spacy_model_es_small:1

Hope you enjoy it :)

**Comment by adriaanbd** [comment]
Thanks a lot 💯 , I'll go ahead and give that a try. I'm sure I'll enjoy it!
