### ISSUE TITLE
Request: langdetect and translate

### ISSUE THREAD

**Issue by adriaanbd** [keithrozario/Klayers#112]
**Additional Packages**:

1. The library `detectlang` is useful to detect the language of a text, to be able to use a correct spacy model, or to be able to translate the text from one language to another. The tar file can be found [here](https://files.pythonhosted.org/packages/56/a3/8407c1e62d5980188b4acc45ef3d94b933d14a2ebc9ef3505f22cf772570/langdetect-1.0.8.tar.gz) and the pypi page [here](https://pypi.org/project/langdetect/).

2. The library `translate` is self-explanatory. The pypi page is [here ](https://pypi.org/project/translate/) and the tar file is over [here](https://files.pythonhosted.org/packages/1f/ab/5d5987a6fcea1ab8785ca6100c4d3ef8c53069633626121026e26cb37a23/translate-3.5.0.tar.gz).

These two libraries are great add-ons and complement to the spacy and pytesseract layers already provided. 

Thanks a lot for your time, if I can do anything to help out, let me know!

**Comment by keithrozario** [comment]
can you make a pull requests to this file:
Klayers/pipeline/config/Klayers-prodp38/packages.csv

**Comment by adriaanbd** [comment]
For sure, I'll do that, thanks! I'll keep my fingers crossed :)

**Comment by adriaanbd** [comment]
Done, it's here #114. Hoping it succeeds 💯
