### ISSUE TITLE
Scikit-learn 

### ISSUE THREAD

**Issue by pmayd** [keithrozario/Klayers#116]
** Additional Packages**:
I would like to request the adding of a scikit-learn layer as it is the main general purpose machine learning library

**Comment by adriaanbd** [comment]
Hi @pmayd, confirming that [this](https://pypi.org/project/scikit-learn/) the package requested?

**Comment by pmayd** [comment]
Correct

**Comment by keithrozario** [comment]
Hey guys, sorry, but I just checked and the size of this package exceeds the limit of lambda (50MB zipped):

"An error occurred (RequestEntityTooLargeException) when calling the PublishLayerVersion operation: Request must be smaller than 69905067 bytes for the PublishLayerVersion operation"

**Comment by pmayd** [comment]
This is why I published the layer via S3. Once the layer is created you can delete S3 again
