### ISSUE TITLE
[FEATURE] Add pyarrow layer

### ISSUE THREAD

**Issue by berzoidberg** [keithrozario/Klayers#119]
Need pyarrow to work w/parquet data in lambda

** Additional Packages**:
Only fill this part if you're just requesting an additional package

**Comment by berzoidberg** [comment]
Oh derp, I see you already have it. I didn't see it previously.

**Comment by berzoidberg** [comment]
Nevermind, that's a different arrow...

**Comment by keithrozario** [comment]
@adriaanbd unlike scikit-learn, this can be built, do you mind taking this up and making a pull requests to close this? Similar to pika as well :)

**Comment by adriaanbd** [comment]
@keithrozario Sure thing, will do this week

**Comment by keithrozario** [comment]
Thanks @adriaanbd 

Pyarrow info is here: https://api.klayers.cloud/api/v1/layers/latest/us-east-1/pyarrow
