### ISSUE TITLE
[BUG] README corrections.

### ISSUE THREAD

**Issue by KumundzhievMaxim** [keithrozario/Klayers#129]
## Hi there! Thanks for your work, guys! 

Reading the README documentation for the [`Option 2: Download copy of the layer`](https://github.com/keithrozario/Klayers#option-2-download-copy-of-layer) I've found the [unreachable link ](https://boto3.amazonaws.com/v1/documentatio/api/latest/reference/services/lambda.html#Lambda.Client.get_layer_version_by_arn). 
Please, have a glimpse on it and correct if find it necessary, could be beneficial for the keeping docs updated! 
Cheers!

**Comment by keithrozario** [comment]
Thanks. It was a missing 'n' -- I'm still wondering how that typo sneaked in :)

Appreciate the heads-up, this is fixed.
