### ISSUE TITLE
pysftp

### ISSUE THREAD

**Issue by awasilyev** [keithrozario/Klayers#130]
Could you please add pysftp ?

bcrypt==3.2.0
cffi==1.14.3
cryptography==3.2.1
paramiko==2.7.2
pycairo==1.20.0
pycparser==2.20
PyGObject==3.38.0
PyNaCl==1.4.0
pysftp==0.2.9
six==1.15.0

**Comment by keithrozario** [comment]
This was added on Monday 👍 

arn:aws:lambda:ap-east-1:770693421928:layer:Klayers-python38-pysftp:1

replace <ap-east-1> with your region, and it should work :)
