### ISSUE TITLE
[FEATURE] What's the process for requesting new layers?

### ISSUE THREAD

**Issue by ronosaurus** [keithrozario/Klayers#131]
Is creating a feature request for new layers the best way to have items added to Klayers? Is there anything the community can do to help in terms of a pull request to make things easier on Klayers maintainers? I glanced at CONTRIBUTING.md but didn't see anything specific.

I'd like to request a layer for _gtfs-realtime-bindings_:

- https://pypi.org/project/gtfs-realtime-bindings/
- https://developers.google.com/transit/gtfs-realtime/examples/python-sample

**Comment by keithrozario** [comment]
Thanks, I've made some additions to the contributing and readme to address this.

The short story is to make a pull request modifying the `pipeline/config/Klayersprodp38/packages.csv` file.

**Comment by keithrozario** [comment]
Made a tiny addition to the `README.MD` file. This should be able to close it :)
