### ISSUE TITLE
[FEATURE] Add Datadog SDK

### ISSUE THREAD

**Issue by RommelLayco** [keithrozario/Klayers#132]
**Is your feature request related to a problem? Please describe.**
Add new package [datadog](https://pypi.org/project/datadog/). This is a python SDK for interacting with datadog api's. This is different to the existing https://github.com/DataDog/datadog-lambda-python which collects metrics about lambda functions.

**Describe the solution you'd like**

**Additional context**

** Additional Packages**:
Only fill this part if you're just requesting an additional package

**Comment by keithrozario** [comment]
This was added today.
