### ISSUE TITLE
[FEATURE] klayers for psycopg2

### ISSUE THREAD

**Issue by ksachdeva11** [keithrozario/Klayers#136]
**Is your feature request related to a problem? Please describe.**
Can we please add a klayer for `psycopg2` ?

**Describe the solution you'd like**
Region - `us-west-2`
Python version - `3.6`

**Additional context**

** Additional Packages**:
Only fill this part if you're just requesting an additional package

**Comment by keithrozario** [comment]
Sorry I got an error while trying to build this -- suspect we don't have the right .so files to build this. Will investigate more.

**Comment by ConnorWilloughby2** [comment]
Would love to see this one too!

**Comment by keithrozario** [comment]
Hey guys, would somebody be able to test if this layer works with an actual database?

arn:aws:lambda:ap-southeast-1:908645878701:layer:pylayers-python38-defaultaws-psycopg2:1

once confirmed, I'll publish it officially across all regions.

**Comment by taku-takamatsu** [comment]
@keithrozario - happy to test on us-east-1

**Comment by keithrozario** [comment]
Thanks @taku-takamatsu . 

Please use this arn: 

arn:aws:lambda:ap-southeast-1:908645878701:layer:pylayers-python38-defaultaws-psycopg2:1

**Comment by taku-takamatsu** [comment]
@keithrozario Sorry, can't test that region. Happy to test on us-east-1!

**Comment by keithrozario** [comment]
My mistake :)

Here's the correct arn:
arn:aws:lambda:us-east-1:908645878701:layer:pylayers-python38-defaultaws-psycopg2:1

**Comment by taku-takamatsu** [comment]
@keithrozario Works great! Thanks.

**Comment by keithrozario** [comment]
Cool, this has been added. Will get built on monday :)

Thanks @taku-takamatsu

**Comment by keithrozario** [comment]
Closing this. Thanks @taku-takamatsu for the testing.

Layers for psycopg2 is here:

https://api.klayers.cloud/api/v1/layers/latest/{region}/aws-psycopg2

replace region with your preferred aws region (e.g. us-east-1)
https://api.klayers.cloud/api/v1/layers/latest/us-east-1/aws-psycopg2
