### ISSUE TITLE
[FEATURE] Could you add a layer for urllib2?

### ISSUE THREAD

**Issue by frederikbrammer** [keithrozario/Klayers#137]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

** Additional Packages**:
Only fill this part if you're just requesting an additional package

**Comment by keithrozario** [comment]
Sorry for some reason was unable to build this -- what specific feature or urrlib2 did you require? That urllib3 did not have?

**Comment by keithrozario** [comment]
Closing this -- as I don't think we need a urllib2 package. Let me know if you really need this.
