### ISSUE TITLE
[BUG] Numpy package errors

### ISSUE THREAD

**Issue by ConnorWilloughby2** [keithrozario/Klayers#139]
Similarly to issue 115 i'm receiving an error for the pandas module when attempting to use it in my function. I'm attempting to add pandas for this issue, however i have noticed it with pandas, sql_alchemy and numpy. 

After loading the layer i have simply attempted to import it and this causes the error message listed at the end of this issue. I assumed that this was an issue to do with my lambda configuration how ever after reading issue 115 i assume this is something else? 

Function:
```
import os
import sys
import csv
import time 
import uuid
import boto3
import numpy

from urllib.parse import unquote_plus

def main(event, context):
    s3_client = boto3.client('s3')
    
    for record in event['Records']:
        bucket = record['s3']['bucket']['name']
        key = unquote_plus(record['s3']['object']['key'])
        tmpkey = key.replace('/', '')
        
        download_path = '/tmp/{}{}'.format(uuid.uuid4(), tmpkey)
        s3_client.download_file(bucket, key, download_path)
```

Error: `Unable to import module 'function': Unable to import required dependencies:\nnumpy:`
Region: `us-east-2`
ARN: `arn:aws:lambda:us-east-2:770693421928:layer:Klayers-python38-pandas:23`

**Comment by keithrozario** [comment]
I actually tried this bit of code and it worked (without the S3 piece though). 

Can you paste your full code snippet? (or is that it?) -- will investigate further.

**Comment by ConnorWilloughby2** [comment]
Full code:

```
import os
import sys
import csv
import time 
import uuid
import boto3
import pandas

from urllib.parse import unquote_plus

def main(event, context):

    s3_client = boto3.client('s3')
    
    for record in event['Records']:
        bucket = record['s3']['bucket']['name']
        key = unquote_plus(record['s3']['object']['key'])
        tmpkey = key.replace('/', '')
        
        download_path = '/tmp/{}{}'.format(uuid.uuid4(), tmpkey)
        s3_client.download_file(bucket, key, download_path)
        ```

**Comment by keithrozario** [comment]
Thanks @ConnorWilloughby2 

I don't see any use of numpy, perhaps for now just remove the layer and import statement, your code doesn't need it 👍 

I'd also suggest using the numpy layer instead of pandas if you only want to use numpy. Hope that helps.

Keith

**Comment by ConnorWilloughby2** [comment]
100% my fault the function was pointing at 3.7 not 8 🤦‍♂️🤦‍♂️🤦‍♂️!
