### ISSUE TITLE
[FEATURE]pymongo layer

### ISSUE THREAD

**Issue by YukunYangNPF** [keithrozario/Klayers#140]
Is your feature request related to a problem? Please describe.
Can we have a layer of pymongo?

Describe the solution you'd like
Region - us-east-1
Python version - 3.8

** Additional Packages**:
Only fill this part if you're just requesting an additional package

**Comment by keithrozario** [comment]
sorry just saw this -- will update over weekend.

**Comment by keithrozario** [comment]
This already exists: arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-pymongo:7
