### ISSUE TITLE
[BUG] Numpy error when using the pandas layer

### ISSUE THREAD

**Issue by samarth12** [keithrozario/Klayers#141]
Hi, this is my first time using Klayers. 

I am trying to using the latest pandas layer which is `arn:aws:lambda:us-west-1:770693421928:layer:Klayers-python38-pandas:24` at the moment. 

I simply import this as a layer using the above mentioned ARN. I am using Python `3.7` for my Lambda function. 

Here is the error I get - 

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': Unable to import required dependencies:
numpy: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/var/lang/bin/python3.7"
  * The NumPy version is: "1.19.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

My Lambda code snippet, I am not doing much just trying to import pandas to see if I can get it to run - 

```
import json
import boto3
import io
import pandas as pd

def lambda_handler(event, context):
    
    bucket_name = event['Records'][0]['s3']['bucket']['name']
    bucket_key = event['Records'][0]['s3']['object']['key']
    
    return {
        'statusCode': 200
}

```

I tried loading the numpy layer before pandas to see if that helps but I still get the same error. Am I missing a step? Thanks in advance for looking at this issue!

**Comment by keithrozario** [comment]
Hey @samarth12,

thanks for using the layers. Unfortunately, we only support python3.8 for the newer layers. Would it be possible for you to change the runtime to 3.8? Based on your code snippet, I don't think this will be a problem -- but if you're using something specific to 3.7, there still might be a workaround.

Let me know.

Keith

**Comment by samarth12** [comment]
Hi @keithrozario, 

Yes, that was it! Thanks a lot! 

So as a future reference Klayers will usually be supporting the latest versions on Lambda?

**Comment by keithrozario** [comment]
Yea, I'll need to workout when Python3.9 comes online, but for now only 3.8 :(
