### ISSUE TITLE
Upgrade Spacy to version 3

### ISSUE THREAD

**Issue by viantirreau** [keithrozario/Klayers#148]
Hi!

First of all, thanks for this awesome work! I'm currently training some language models on Spacy's latest version (3.0.3 as of today), and I'm really excited to test and deploy them in a serverless fashion. Despite this major version being released about two weeks ago, it seems like the latest ARN for Spacy still points to version 2.3.5.
I don't fully comprehend the details of the weekly deploys yet, but this package lists the latest Spacy version as a requirement
https://github.com/keithrozario/Klayers/blob/c0e8c98745cf90edccf15fe30d86959f19aca358/deployments/python3.8/packages/spacy/requirements.txt#L19

Does the upgrade to version 3 have to be manually configured or will it be updated automatically soon?
If it's the former case, let me know if I can help with a PR in some way :)

Thanks in advance!

EDIT: 
I was able to deploy Spacy v 3.0.3 manually as a layer, although it wasn't straightforward. The default package size exceeded 50 MB compressed (mainly because of a new dependency, Pydantic, which adds roughly 30 MB). I managed to delete all of Pydantic's `.so` shared library files and it still worked for my use case. We could even optimize it further by stripping the remaining (and essential) `.so` binaries and deleting some tests / caches

**Comment by keithrozario** [comment]
Thanks @viantirreau , in theory spacy deployments should happen automatically, and provide the latest version. But the automatic builds were failing (possibly due to the issue you mention).

**Comment by jacarrasco** [comment]
Hello @viantirreau , could you please share the details to upload Spacy version 3 as layer? I am facing the same issue, i tried to remove some packages but still it is biggest than 250 Mb. 
If we figure out it would be great to have a PR for this project so everybody can have latest version.

**Comment by keithrozario** [comment]
HI folks, as long as someone can provide me a zipped version of the spacy layer, I can upload it across and share.

**Comment by viantirreau** [comment]
Hi @keithrozario  and @jacarrasco!
Sure, I will zip the latest version (3.0.6 as of right now) and post the link here soon :)

**Comment by viantirreau** [comment]
Hi again!
You can download the zip file from [here](https://drive.google.com/file/d/17_Cp3XmURXCwEwHsqHS75BlMSnOAVQpR/view?usp=sharing).
Although this may not integrate well on @keithrozario's automatic deployment pipeline, I made a [gist](https://gist.github.com/viantirreau/d7520fdc932d83c43a5f40afe48cc60f) with a script that automates this process, at least locally :)


Let me know if something breaks. I just tested it on AWS and worked flawlessly on a simple TextCat model.

**Comment by jacarrasco** [comment]
Thank you @viantirreau , funciona perfectamente! :)

**Comment by viantirreau** [comment]
Genial @jacarrasco, me alegro que haya funcionado! 🎉

**Comment by keithrozario** [comment]
hi @viantirreau was this for python3.7 or python3.8?

**Comment by keithrozario** [comment]
Thanks, @viantirreau , now the spacy 3.0.6 layer is available for all regions. Later layer version can be obtained by querying the api, e.g https://api.klayers.cloud/api/v1/layers/us-east-1/spacy
