### ISSUE TITLE
[FEATURE] Can you please add a layer for regex.

### ISSUE THREAD

**Issue by ju9aid** [keithrozario/Klayers#151]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

** Additional Packages**:
Only fill this part if you're just requesting an additional package

**Comment by keithrozario** [comment]
Sorry, I'm no longer taking additional packages as issues. Apologies it took a while to respond. 

If you would like a new package to be made a layer, raise a pull request modifying the pipeline/config/Klayers-prodp38 file.
