### ISSUE TITLE
[FEATURE] gzip layer

### ISSUE THREAD

**Issue by bvandermeersch** [keithrozario/Klayers#152]
** Additional Packages**:
Can we get a gzip layer?
As its missing in the aws lambda python 3.8 runtime

**Comment by keithrozario** [comment]
Sorry, I'm no longer taking additional packages as issues. Apologies it took a while to respond. 

If you would like a new package to be made a layer, raise a pull request modifying the pipeline/config/Klayers-prodp38 file.
