### ISSUE TITLE
[FEATURE] datatable module

### ISSUE THREAD

**Issue by Peter-Pasta** [keithrozario/Klayers#153]
Please consider adding  the datatable module to this repository. You can check it out here https://github.com/h2oai/datatable. 

Thank you.

**Comment by keithrozario** [comment]
Sorry, I'm no longer taking additional packages as issues. Apologies it took a while to respond. 

If you would like a new package to be made a layer, raise a pull request modifying the pipeline/config/Klayers-prodp38 file.
