### ISSUE TITLE
[BUG]  cannot import name '_imaging' from 'PIL'

### ISSUE THREAD

**Issue by merc1er** [keithrozario/Klayers#154]
**Describe the bug**

I am getting the following error when importing anything from `PIL` using the Pillow ARN.

```
{
  "errorMessage": "Unable to import module 'lambda_function': cannot import name '_imaging' from 'PIL' (/opt/python/PIL/__init__.py)",
  "errorType": "Runtime.ImportModuleError",
  "stackTrace": []
}
```

**Layer Version ARN:**

Pillow 8.2.0 in `ap-southeast-1` for Python 3.8.

`arn:aws:lambda:ap-southeast-1:770693421928:layer:Klayers-python38-Pillow:10`

**Framework:**

Just console.

**Additional context**

Here is my code:

```python
from PIL import Image


def lambda_handler(event, context):
    return {
        "statusCode": 200,
        "body": "OK",
    }
```

Same thing when I do:

```python
import PIL

PIL.Image()
```

I am using the `boto3` layer, and this one is working fine when I import it.

**Comment by DylanAlbertazzi** [comment]
I'm having the same issue in us-west-2

**Comment by DylanAlbertazzi** [comment]
It looks like Pillow no longer supports _imaging. See the bottom warning https://pillow.readthedocs.io/en/4.2.x/installation.html
"Pillow >= 2.1.0 no longer supports “import _imaging”. Please use “from PIL.Image import core as _imaging” instead."

**Comment by keithrozario** [comment]
Thanks @DylanAlbertazzi , does that mean there's nothing wrong with the layer?

**Comment by DylanAlbertazzi** [comment]
@keithrozario yep. The layer still works fine 🙂

Side question... Do you know if layers work with lambda function running on greengrass for IoT devices?

I'm guessing you can't because I can't get them to work and don't see any documentation mentioning anything about it.

**Comment by merc1er** [comment]
> It looks like Pillow no longer supports _imaging

I am not importing _imaging @DylanAlbertazzi

**Comment by DylanAlbertazzi** [comment]
@merc1er Are you trying to run it on Amazon Linux?

**Comment by subratamal** [comment]
It's not working with me with a very similar setup. There is not much error context as well.
Is there a need to set the PATH variable manually?

**Comment by nuffertaylor** [comment]
if anyone else sees this issue, this was my problem:
my lambda runtime was python 3.9, but the max runtime for this klayer is 3.8. switching to 3.8 resolved everything

**Comment by dwei-grubmarket** [comment]
> if anyone else sees this issue, this was my problem: my lambda runtime was python 3.9, but the max runtime for this klayer is 3.8. switching to 3.8 resolved everything

Agreed, actually its only caused by this python runtime version descrepency, thank you!

**Comment by kxngdavid** [comment]
Can someone please confirm if changing the python runtime to 3.8 still works? cause I did that but I'm still getting the same error.

**Comment by Adorp94** [comment]
@kxngdavid @jasonrdunne Did you got to resolve it?

**Comment by Adorp94** [comment]
This [medium post](https://derekurizar.medium.com/aws-lambda-python-pil-cannot-import-name-imaging-11b2377d31c4) helped me resolve it.
I had to change the python runtime to 3.8 (both on lambda and the layer). And then add the layer from the ARN, there's a list metioned on the medium post.

**Comment by kxngdavid** [comment]
Thanks Jason!

Really appreciate!

**Comment by SAINTZST** [comment]
> if anyone else sees this issue, this was my problem: my lambda runtime was python 3.9, but the max runtime for this klayer is 3.8. switching to 3.8 resolved everything

AWS will block python3.8 from function create/update soon. So, I'm using python3.9. The layer from the repo working well (This ARN `arn:aws:lambda:ap-southeast-2:770693421928:layer:Klayers-p39-pillow:1`) But when I build the layer myself it throws the same message. Anyone has any idea?

(I did pip install pillow in the linux env via docker, All other packages work fine except for pillow)

**Comment by numairmansur** [comment]
`arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38Pillow:5` does not work for me for Python3.8
