### ISSUE TITLE
[BUG] OpenCV libthread-2.0.so.0 missing

### ISSUE THREAD

**Issue by adarshworkduck** [keithrozario/Klayers#156]
Open cv isn't working as expected I believe. This is the error:
{
  "errorMessage": "Unable to import module 'lambda_function': libgthread-2.0.so.0: cannot open shared object file: No such file or directory",
  "errorType": "Runtime.ImportModuleError"
}

**Comment by keithrozario** [comment]
Duplicate with #115

**Comment by keithrozario** [comment]
I'll try to see if I have time this week to look into it

**Comment by keithrozario** [comment]
Fix is available, refer to #115
