### ISSUE TITLE
Errror: Unable to download Layer by ARN

### ISSUE THREAD

**Issue by adarshworkduck** [keithrozario/Klayers#157]
How can I download the klayers?

response = client.get_layer_version_by_arn(
                    Arn='arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python38-SciPy1x:29'
                )
I tried this. And am getting the following error:

Response
{
  "errorMessage": "An error occurred (AccessDeniedException) when calling the GetLayerVersionByArn operation: User: arn:aws:sts::418506370286:assumed-role/workduck-api-dev-us-east-1-lambdaRole/lambdaTest3 is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python38-SciPy1x:29",
  "errorType": "ClientError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 16, in lambda_handler\n    response = client.get_layer_version_by_arn(\n",
    "  File \"/var/runtime/botocore/client.py\", line 357, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
    "  File \"/var/runtime/botocore/client.py\", line 676, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"
  ]
}

Can you give a brief about how did you make these layers? I tried pip installing the libraries and uploading them but am facing issues.

**Comment by keithrozario** [comment]
hi @adarshworkduck , this isn't a Klayer layer unfortunately, I can't comment.

But you can do the same for any one of the layers in this repo, and it should work. (if it doesn't let me know).
