### ISSUE TITLE
[BUG] Import cv2 fails in AWS Lambda for Python 3.8

### ISSUE THREAD

**Issue by ganesh3** [keithrozario/Klayers#160]
**Describe the bug**
I have used the ARNs for ap-south-1 region for opencv and imported it for python 3.8. I am getting the below error:

 {
 "errorMessage": "Unable to import module 'lambda_function': libgthread-2.0.so.0: cannot open shared object file: No such file or directory",
  "errorType": "Runtime.ImportModuleError",
  "stackTrace": []
}

**Screenshots**

**Layer Version ARN:**
Specific Layer ARN that didn't work (let's us know which version, region etc).
arn:aws:lambda:ap-south-1:770693421928:layer:Klayers-python38-opencv-python-headless:11

**Framework:**
What Framework do you use (Serverless, Architect, Zappa, or just Console?)
Console

**Additional context**

**Comment by keithrozario** [comment]
Fix is available, refer to #115
