### ISSUE TITLE
[FEATURE] Could you please provide sklearn and flask layers for us-west-2?

### ISSUE THREAD

**Issue by ksachdeva11** [keithrozario/Klayers#169]
**Is your feature request related to a problem? Please describe.**
I am looking for sklearn and flask layers for my lambda. Any help would be very much appreciated.

**Describe the solution you'd like**
Lambda layers for sklearn and flask on us-west-2.

**Comment by keithrozario** [comment]
If you need sklearn please add a pull request for the layer. Instructions on how to do it are at the bottom of the README.
