### ISSUE TITLE
[BUG] pymongo missing module for atlas URI access 

### ISSUE THREAD

**Issue by rchardb** [keithrozario/Klayers#190]
"errorMessage": "The \"dnspython\" module must be installed to use mongodb+srv:// URIs. To fix this error install pymongo with the srv extra:\n /var/lang/bin/python3.8 -m pip install \"pymongo[srv]\""

extra packages need to be installed using  pip install \"pymongo[srv]\" to support URI names and allowing easy access to atlas mongodb

**Comment by rchardb** [comment]
Would it be possible to modify command to include necessary packages?
The following command includes additional packages to support named URI (dnspython)

pip install "pymongo[srv]"

**Comment by keithrozario** [comment]
If you make a pull request, requesting for package named `pymongo[srv]` that might resolve your issue. Would you be able to do that?
