### ISSUE TITLE
[FEATURE] supporting LTS versions and not automatically deleting them

### ISSUE THREAD

**Issue by alonisser** [keithrozario/Klayers#198]
**Is your feature request related to a problem? Please describe.**
First: Thanks for this great project!
Currently layers are deprecated and getting expired on each new version, for example 
https://api.klayers.cloud/api/v1/layers/eu-west-1/SQLAlchemy
returns "SQLAlchemy==1.4.28" as latest and 3 three other deprecated versionsץ
The problem is while minor versions are good, I'm not inclined into accidentally breaking my lambda because of a version change in SQLalchemy.. and currently, there is no supported way to specify an LTS version of SQLalchemy that won't be expired after 60 days from next patch version
**Describe the solution you'd like**
Adding an LTS version to "latest" and "deprecated" that would exist for a longer cycle the current 60 days after the new version

**Additional context**

** Additional Packages**:

**Comment by alonisser** [comment]
Another, perhaps more viable option, because not libraries have a concept of LTS, is to allow a "major" version, which underneath would be the alias to the the latest automated layer from the same library

**Comment by keithrozario** [comment]
Latest release, now keep the latest version for at 365 days vs. 60 days from before.

Many folks have requested this, and keeping the layers longer help a lot of folks as well.
