### ISSUE TITLE
[FEATURE] 3.9 pandas layer optional dependencies

### ISSUE THREAD

**Issue by gergo-szabo** [keithrozario/Klayers#211]
Pandas layer for Python 3.9 can't handle excel files.

The supporting lib-s are listed as optional dependecies but the layer might have space for them.

Details about optional dependencies:
https://pandas.pydata.org/docs/getting_started/install.html#optional-dependencies

**Comment by keithrozario** [comment]
Would you be able to make a pull request for the right packages -- I'd like to keep packages minimal. And anyone that wants to combine packages can use multiple layers to include the right dependencies.

**Comment by gergo-szabo** [comment]
This feature "request" was more of a notification on an improvement potential. I have already created a supplementary layer for my optional dependecy. Feel free to close it if you would like to keep creating lean packages.
Anyway, thanks for the pandas package.

**Comment by keithrozario** [comment]
Thanks. Yes prefer to keep layers lean, as not everyone needs the additional packages, and Lambda has a size limit on how much can be packed into layers.

Thanks for the support!
