### ISSUE TITLE
[BUG] Python 3.9 SqlAlchemy Requires psycopg2 for Postgresql

### ISSUE THREAD

**Issue by vincentdory** [keithrozario/Klayers#217]
**Describe the bug**
Hello,

The SqlAlchemy layer for Python 3.9 is currently unusable for querying Postgresql servers due to SqlAlchemy requiring psycopg2 to work properly. The first screenshot is the result of a test where the only layer present in my function is the Python 3.9 Klayer for SqlAlchemy, it fails because psycopg2 isn't present. 

I tried using the python 3.8 klayer for psycopg2, and the second screenshot is the result. From what I understand from searching online, this is a compatibility issue with the psycopg2 layer being built for python version 3.8.

So, a version of psycopg2 klayer needs to be created for Python 3.9.

**Screenshots**
![image](https://user-images.githubusercontent.com/97315600/170381903-e017528e-5549-4635-a867-e7562a9bca4a.png)
![image](https://user-images.githubusercontent.com/97315600/170382715-b7630a52-80f2-4fb2-abb9-f1d5ac0ec84d.png)

**Layer Version ARN:**
arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-SQLAlchemy:2
arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-aws-psycopg2:1

**Framework:**
Serverless and Console

**Additional context**
Thanks for the help!

**Comment by keithrozario** [comment]
Can you try with this layer? arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-psycopg2-binary:1 

Not sure if it'll work.

**Comment by vincentdory** [comment]
Hey, that worked! Thank you very much!

You can close this, hopefully google will pick it up so others will find the solution.

**Comment by keithrozario** [comment]
awesome!!
