### ISSUE TITLE
aws-lambda-powertools version 10 missing dependencies 

### ISSUE THREAD

**Issue by kevin-burns** [keithrozario/Klayers#234]
using the layers request 
`https://api.klayers.cloud/api/v2/p3.8/layers/eu-central-1/aws-lambda-powertools`
the layer that is returned is missing dpeendencies such as xray-sdk, with error message in Lambda logs 
`No module named 'aws_xray_sdk'` 

Rolling back to use version 9 as a fix resolves any runtime issues you might see with Lambda

**Comment by keithrozario** [comment]
I suspect they removed the dependency in the latest version. If you wish to use xray, you can try using two layers at once:

e.g. Powertools + the one below:
arn:aws:lambda:eu-central-1:770693421928:layer:Klayers-p38-aws-xray-sdk:12
