### ISSUE TITLE
arn:aws:lambda:eu-west-1:770693421928:layer:Klayers-python38-Pillow:15 doesn't exist

### ISSUE THREAD

**Issue by Chris59160** [keithrozario/Klayers#246]
Hello,

I was doing a deployment of my stacks, where I reference the Pillow layer, and it basically keep saying that 
arn:aws:lambda:eu-west-1:770693421928:layer:Klayers-python38-Pillow:15

Doesn't exist any more.

Was it removed accidently or the URL has changed ?

region: eu-west-1
lib: Pillow

Thanks,

Chris

**Comment by Thestias** [comment]
Happened the same to me but with Pandas, seems that the layer ARNs have changed:

According to the JSON in the repo's README for Pillow now its:

`arn:aws:lambda:eu-west-1:770693421928:layer:Klayers-p38-Pillow:6`

**Comment by keithrozario** [comment]
Thanks @Thestias , you're indeed correct the layers do change over time.

Generally now, we update the layers monthly, and keep a deprecated layer for 365 days. Once the 365 days has past the layer is deleted -- and any 'new' deployments referencing the layer will fail. Existing lambda functions that used the deleted layer will still work though.

To complicate matters 'slightly' -- we shortened the layers names from Klayers-python38-Pillow to Klayers-p38-Pillow. But the principle still applies.
