### ISSUE TITLE
Create new lambda layer for latest version of boto3

### ISSUE THREAD

**Issue by mike-mosher** [keithrozario/Klayers#26]
The version of boto3 included with Lambda functions is horribly out of date (boto3-1.9.42 for python3.7 runtimes) and I hate having to package boto3 every time I make a new function. 

I have used your package.sh script to create lambda layers in my account for boto3 and it worked great! However, I would love to have a public lambda layer that I can reference from any account.  

Please publish a public lambda layer for boto3!!  Would be super appreciated

**Comment by keithrozario** [comment]
Indeed. AWS recommend using your own packaged boto3 rather than the included one. The only reservation I have is that -- it very quickly becomes out of date -- as AWS updates this nearly 2-3 times a week sometimes. I'll do this soon :) thanks for the tip.

**Comment by keithrozario** [comment]
Done. I need to figure out how to make this more manageable though.
