### ISSUE TITLE
[BUG] PyMuPDF AWS-Lambda import error

### ISSUE THREAD

**Issue by gv-sai-kumar** [keithrozario/Klayers#267]
even after loading the layer
arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-PyMUPDF:6 
still not able to import fitz, lambda run time Python 3.9, x86_64

Unable to import module 'lambda_function': cannot import name '_fitz' from partially initialized module 'fitz' (most likely due to a circular import) (/opt/python/fitz/__init__.py)

Can you please let me know how to run this without errors.

**Comment by keithrozario** [comment]
can you try using python3.8 instead.
