### ISSUE TITLE
TesseractNotFoundError for Python 3.7

### ISSUE THREAD

**Issue by chahna107** [keithrozario/Klayers#29]
I am trying to create a Lambda function by using the Pytesseract library for Python 3.7. I also put the Tesseract binaries at the same location.

Tesseract works fine when calling it using the subprocess library. But **pytesseract.image_to_string(image_string)** gives **TesseractNotFoundError**.

I tried to set the **LD_LIBRARY_PATH** and **TESSDATA_PREFIX** both in the script, but that does not make any difference.

Any help will be appreciated! Thanks!

**Comment by keithrozario** [comment]
Did you use the tesseract binary provided by the KLayer repo or did you build it yourself?

There is an example of using the tesseract binary layer and the pytesseract layer here:

https://github.com/keithrozario/Chlorine-40/blob/master/serverless/draw_ocr.py

Although we don’t use the image_to_string but image_to_data instead. You’ll need two layers, the tesseract binary layer AND the pytesseract layer. 

Let me know.

**Comment by chahna107** [comment]
@keithrozario I am using the tesseract binary provided by KLayer repo.
I checked the example that you pointed to and I am doing a similar thing, but I get an error saying:
**TesseractNotFoundError: "tesseract is not installed or it's not in your path"**

I tried using tesseract and pytesseract as Lambda layers. And I also tried zipping the tesseract binaries and pytesseract library in the Lambda function deployment package itself. But none of the approaches seem to work.

Is there anything additional that I need to do in the code or the Lambda function?

**Comment by keithrozario** [comment]
Use them as layers. Do you have a `serverless.yml` file or are you doing this manually through the console?

**Comment by chahna107** [comment]
I am doing it manually. I tried to use them as layers too but no luck :(

**Comment by keithrozario** [comment]
Can you share your code and a screenshot of your lambdas configuration.

**Comment by chahna107** [comment]
Please find the details below.

Here is the structure of the Lambda deployment package. The pytesseract and tesseract are from the KLayers repo. There is no additional configuration for the Lambda function.
![Screen Shot 2019-05-15 at 9 19 39 AM](https://user-images.githubusercontent.com/27863001/57778722-aaba2580-76f2-11e9-9448-8a667aaed335.png)

I tried using tesseract in 2 different ways:
1. Using **tesseract** command - works fine
```
import subprocess
def handler(event, context):
      # Get image as base64 string
      image_string = event["image"]

      command = './bin/tesseract --help'
      output = subprocess.check_output(command, shell=True, stderr=subprocess.STDOUT)
      return output
```
The Lambda output for above code is as below:
![Screen Shot 2019-05-15 at 9 30 24 AM](https://user-images.githubusercontent.com/27863001/57779465-1fda2a80-76f4-11e9-9f96-ff84365c9737.png)

2. Using **pytesseract** with the same package structure - gives **TesseractNotFoundError**
I tried setting and unsetting the **pytesseract.pytesseract.tesseract_cmd** 
```
import pytesseract
import json
import traceback
import os
import subprocess

# pytesseract.pytesseract.tesseract_cmd = './bin/tesseract'

def handler(event, context):
    try:
        # Get image as base64 string
        image_string = event["image"]
        d = pytesseract.image_to_string(image_string)
        print(d)
    except Exception as e:
        d = {"type": e.__class__.__name__, "msg": str(e), "trace": traceback.format_exc()}
        raise Exception(json.dumps(d))
```
The Lambda output for above code:
![Screen Shot 2019-05-15 at 9 35 20 AM](https://user-images.githubusercontent.com/27863001/57779951-3634b600-76f5-11e9-8cb9-d4ee8a189909.png)

**Comment by keithrozario** [comment]
Pytesseract requires that Tesseract be in your path, i.e tesseract can be called directly with the `tesseract` command.

Subprocess works because you’re calling it using a relative path `./bin` but pytesseract will not use this.

I recommend using both of them as layers rather than packaging them into your code. The previous example I shared should work.

The alternative would be to add the packaged tesseract binary to your path, to do this add `/var/task/bin` to your path using os.environ command. 

But please consider just adding both public layers as layers to your lambda — it’ll work better.

**Comment by chahna107** [comment]
@keithrozario Adding the path `/var/task/bin` also gives the same error.

I also tried using the public layers using the ARN, but that also has the same error.

**Comment by keithrozario** [comment]
That’s odd.

I’m not sure if you’re using the `image_to_string_` command correctly.

I will try to replicate the issue, but can only do so in about a weeks time.

**Comment by chahna107** [comment]
Sure. Please let me know if you have any update whenever.
Thanks!

**Comment by keithrozario** [comment]
Hi, I'm unable to replicate your issue.

I setup a function using the layers like so:
![Screenshot 2019-05-26 at 2 31 42 PM](https://user-images.githubusercontent.com/795867/58378260-cf03e500-7fc3-11e9-89c1-db9daf496b8e.png)

and then run the following [code](https://gist.github.com/keithrozario/7c66a4edce34abd601397b70547624c6)

**Comment by chahna107** [comment]
I tried it again and worked for me this time. Not sure what I was doing wrong back then!
Thanks though for the help.

However, the **image_to_string** function works fine. But my main task is to use **image_to_boxes**. That function is not able to generate the **.box** file on Lambda and so it gives the error saying _No such file or directory_.
Do you have any idea why that particular function is not working?

**Comment by keithrozario** [comment]
you need to write all files to the `/tmp` directory, which is the only writeable directory in the lamda container.

e.g `/tmp/.box`

**Comment by chahna107** [comment]
I checked the contents of `/tmp` and the issue is that the function **image_to_boxes** writes the .PNG and .txt file. But does not write the .box file.

**Comment by keithrozario** [comment]
Ok. Thanks.

Sounds like the issue is closed then. Hope you enjoyed using the layers.
