### ISSUE TITLE
[BUG] urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips

### ISSUE THREAD

**Issue by ekelmann** [keithrozario/Klayers#352]
Describe the bug
I'm trying to integrate requests into a Python 3.8 Lambda function. However, I'm encountering the following error message: "[BUG] urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips'."

Screenshots
N/A

Layer Version ARN:
arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-requests:14

<br class="Apple-interchange-newline">

Framework:
Lambda Function with Python 3.8

Additional context
It seems that there is a compatibility issue between urllib3 version 2.0 and the OpenSSL version used by the 'ssl' module in Python 3.8. This issue prevents the successful integration of requests in my Lambda function. I would appreciate any guidance or suggestions on how to resolve this issue.

**Comment by keithrozario** [comment]
Yes, unfortunately, this is a known issue with some conflict in dependencies for Requests and Urrlib :(

https://github.com/keithrozario/Klayers/issues/305

Solution for now is to use the non-latest version. Try arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p38-requests:13 (or 11/12).
