### ISSUE TITLE
[BUG] The layer version show the message: "This layer no longer exists. You must remove this layer from the list before you can save any changes"

### ISSUE THREAD

**Issue by haochiu28** [keithrozario/Klayers#353]
**Describe the bug**
Hello, we use Terraform to deploy Lambda, and we used requests, PyJWT, cryptography these three Layers.
Terraform is using the latest version of Klayers Layer, but the latest version does not work on Lambda layer.

This Issue is similar to Issue#305(https://github.com/keithrozario/Klayers/issues/305)

**Screenshots**
The layer version show the message: "This layer no longer exists. You must remove this layer from the list before you can save any changes"
![Screenshot 2023-07-06 at 11 03 53](https://github.com/keithrozario/Klayers/assets/124852610/272b6c8d-7426-4872-97a9-1f2c11e7f179)

But the latest layer version list shows
![Screenshot 2023-07-06 at 11 16 33](https://github.com/keithrozario/Klayers/assets/124852610/a54fc897-4172-4dce-999b-ebf3fe86228f)

**Layer Version ARN:**
arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p39-requests:15
arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p39-PyJWT:2
arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p39-cryptography:14

**Framework:**
Serverless

**Additional context**
We lowered the Layer version and it works fine.
arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p39-requests:11
arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p39-PyJWT:1
arn:aws:lambda:us-east-2:770693421928:layer:Klayers-p39-cryptography:11

Lambda Runtime settings:
Runtime: Python3.9
Architecture: x86_64
Region: us-east-2(US East(Ohio))

**Comment by keithrozario** [comment]
It seems to be a quirk in the console UI, I am able to add it:
![image](https://github.com/keithrozario/Klayers/assets/795867/c2a749d4-e595-4065-b4e4-bdf9c496081e)

I get the same error as you, but just clicking "Save" still works and will continue.
![image](https://github.com/keithrozario/Klayers/assets/795867/012f77f6-d6b4-4aa5-9e7b-9c8e4ac82e56)
