### ISSUE TITLE
Create new lambda layer for pytz

### ISSUE THREAD

**Issue by ImperialXT** [keithrozario/Klayers#36]
I was wondering if you'd be willing to create a public layer for pytz. As it's not included in lambda and datetime sucks at dealing with timezones...

**Comment by keithrozario** [comment]
sure, can you try making a pull request adding one line to the packages/deploy_all.sh script, and making a pull request?

need to check the license agreement of the module before adding it.

**Comment by keithrozario** [comment]
done.

arn:aws:lambda:\<*region*>:113088814899:layer:Klayers-python37-pytz:1

**Comment by ImperialXT** [comment]
Thank you.

**Comment by keithrozario** [comment]
Your Welcome. Appreciate it if you could star the repo as well -- stars count a lot :)

**Comment by pratik3221** [comment]
Will this be compatible with python 3.9 as well?
