### ISSUE TITLE
[FEATURE] Additional Package - PyJWT

### ISSUE THREAD

**Issue by ybhwang** [keithrozario/Klayers#363]
**Is your feature request related to a problem? Please describe.**

It would be nice if a package that could handle JWT was added.

**Describe the solution you'd like**

It seems to be advantageous for interacting with the `cryptography`.

**Additional context**

https://github.com/jpadilla/pyjwt

**Additional Packages**

- [PyJWT](https://pypi.org/project/PyJWT)

**Comment by keithrozario** [comment]
Can raise a PR instead of an Issue?

**Comment by keithrozario** [comment]
Can you raise a pull requests. I'll be happy to merge it.

**Comment by AMO-brandon** [comment]
How often do you merge pull requests? I have one open.

**Comment by keithrozario** [comment]
I merged these yesterday. Sorry for the delay.

**Comment by ybhwang** [comment]
> Can raise a PR instead of an Issue?

Can you provide a list of files I need to modify for this task and a brief modification guide?

**Comment by keithrozario** [comment]
[Asking for additional layers](https://github.com/keithrozario/Klayers#asking-for-additional-layers)
If you would like a new package to be made a layer, raise a pull request modifying the pipeline/config/packages_p310.csv or pipeline/config/packages_p310-arm64.csv file (depending on which architecture you prefer). By default, please request for the latest version of python unless you absolutely need an older version.
