### ISSUE TITLE
[BUG] Pytesseract - can not open libpng12 so 

### ISSUE THREAD

**Issue by MittalShruti** [keithrozario/Klayers#372]
**Describe the bug**
While running pytesseract, I am getting this error 

`[ERROR] TesseractError: (127, 'tesseract: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory')
`
using the code [here](https://gist.github.com/keithrozario/7c66a4edce34abd601397b70547624c6)

**Screenshots**
![pytesseract](https://github.com/keithrozario/Klayers/assets/5301961/1bab3968-a619-478b-8d9a-68e35481a924)

**Layer Version ARN:**
I am using pytesseract layer for us-west-2 and the tesseract layer as shown in the screenshot below.

**Framework:**
Serverless

**Comment by keithrozario** [comment]
Do you have teaseract install. The layer I have only has the Pytesseract library and not the actual tesseract binary.
