### ISSUE TITLE
[FEATURE] python3.12 support

### ISSUE THREAD

**Issue by Krsnik0** [keithrozario/Klayers#375]
Is aws lambda python3.12 support available?

AWS has published python3.12 runtime for lambda [link](https://aws.amazon.com/ko/about-aws/whats-new/2023/12/aws-lambda-support-python-3-12/)

It would be great to have layers available for Python 3.12 as well
Thank you for Klayers :)

**Comment by keithrozario** [comment]
Thanks. Will get to this early next year? When I'm back from Christmas break :)

**Comment by keithrozario** [comment]
Happy to report this is one in the latest release :).

Happy building.

**Comment by keithrozario** [comment]
Done https://github.com/keithrozario/Klayers/tree/v2024-01.1

**Comment by Krsnik0** [comment]
Thank you!
and Happy New Year :)
