### ISSUE TITLE
[BUG] Type for title on Python 3.12 arm64 layers

### ISSUE THREAD

**Issue by credizian** [keithrozario/Klayers#385]
**Describe the bug**
The title still says "3.11" instead of "3.12"

Here's the link: https://github.com/keithrozario/Klayers/tree/master/deployments/python3.12-arm64

p.s. You guys are awesome!!

**Comment by keithrozario** [comment]
Thanks. Fixed in https://github.com/keithrozario/Klayers/pull/386

Appreciate the love!
