### ISSUE TITLE
need openai layers

### ISSUE THREAD

**Issue by Gowthaman0225** [keithrozario/Klayers#387]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

** Additional Packages**:
Only fill this part if you're just requesting an additional package

**Comment by janpmz** [comment]
I need that layer as well.

**Comment by keithrozario** [comment]
Merged in https://github.com/keithrozario/Klayers/pull/388

arn:aws:lambda:{region}:770693421928:layer:Klayers-p310-openai:1
