### ISSUE TITLE
[FEATURE] Adding PyJWT to py3.10 layers

### ISSUE THREAD

**Issue by philmonnot** [keithrozario/Klayers#416]
**Is your feature request related to a problem? Please describe.**

This is a request to add a py3.10 layer with the PyJWT package.

**Describe the solution you'd like**

As above.

**Additional context**

- https://github.com/jpadilla/pyjwt

** Additional Packages**:

- https://pypi.org/project/PyJWT/

**Comment by keithrozario** [comment]
Can you make a pull requests to the repo instead. Modify the csv files under pipeline/config.

Preferably choose Python 3.12 instead of 3.10 unless you have a specific reason to use an older version of Python.

**Comment by KevsterAmp** [comment]
@keithrozario I'd like to work on this, can you assign this issue to me? Thanks

**Comment by keithrozario** [comment]
Go ahead and raise a PRinmed to this.
