### ISSUE TITLE
API does not filter on {package}

### ISSUE THREAD

**Issue by petersmythe** [keithrozario/Klayers#426]
API does not appear to filter on {package}:

Example from [docs](https://github.com/keithrozario/Klayers?tab=readme-ov-file#get-all-arns-for-specific-package-in-region):  
 
https://api.klayers.cloud/api/v2/p3.9/layers/ap-southeast-1/boto3

this returns all v3.9 packages in ap-southeast-1

I expect it to only return the boto3 package ARN

**Comment by keithrozario** [comment]
For me at least this works correctly: 
![image](https://github.com/user-attachments/assets/bfa9a762-4140-454b-a99a-0214c60dfa36)

Can you elaborate more -- the endpoint does provide some 'other' packages, but those are the dependencies of the package in question. i.e. boto3 will install those packages (like jmespath).
