### ISSUE TITLE
[BUG] - AWS Lambda: cannot import name '_imaging' from 'PIL'

### ISSUE THREAD

**Issue by vikramb06** [keithrozario/Klayers#430]
Hey Klayers Team,

Coming across an issue while using the Klayers Pillow layer with the ARN - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p312-Pillow:3
Unable to use **_amazon-textract-textractor 1.8.2_** which has a dependency on PIL while running through Lambda.
Getting the following error - AWS Lambda: cannot import name '_imaging' from 'PIL'

Tried using Klayers PIL for 3.8, 3.10 and 3.12 - same error.
Appreciate any help regarding this issue with Lambda and Klayers.

**Screenshots**
<img width="1071" alt="Screenshot 2024-08-02 at 6 26 30 PM" src="https://github.com/user-attachments/assets/83e66c0e-7555-4638-bd89-34507f8ebe6c">

**Layer Version ARN:**
ARN - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p312-Pillow:3
Region - US-EAST-1

**Framework:**
Lambda, Python 3.12

Thanks!

**Comment by keithrozario** [comment]
Are you able to provide a code snippet?

**Comment by vikramb06** [comment]
Sure, the imports are being done in the [Textractor library](https://pypi.org/project/amazon-textract-textractor/).
`from textractor import Textractor`
-> `from PIL import Image`
-> 
`try:
    # If the _imaging C module is not present, Pillow will not load.
    # Note that other modules should not refer to _imaging directly;
    # import Image and use the Image.core variable instead.
    # Also note that Image.core is not a publicly documented interface,
    # and should be considered private and subject to change.
    from . import _imaging as core

    if __version__ != getattr(core, "PILLOW_VERSION", None):
        msg = (
            "The _imaging extension was built for another version of Pillow or PIL:\n"
            f"Core version: {getattr(core, 'PILLOW_VERSION', None)}\n"
            f"Pillow version: {__version__}"
        )
        raise ImportError(msg)

except ImportError as v:
    core = DeferredError.new(ImportError("The _imaging C module is not installed."))
    # Explanations for ways that we know we might have an import error
    if str(v).startswith("Module use of python"):
        # The _imaging C module is present, but not compiled for
        # the right version (windows only).  Print a warning, if
        # possible.
        warnings.warn(
            "The _imaging extension was built for another version of Python.",
            RuntimeWarning,
        )
    elif str(v).startswith("The _imaging extension"):
        warnings.warn(str(v), RuntimeWarning)
    # Fail here anyway. Don't let people run with a mostly broken Pillow.
    # see docs/porting.rst
    raise`

**Comment by vikramb06** [comment]
Hey @keithrozario 
I fixed this issue by using the Textractor as one of the layers in my Lambda function.
Found the Textractor layer [here](https://github.com/aws-samples/amazon-textract-textractor/actions/runs/9663648259).

Closing this issue - thanks again!

**Comment by keithrozario** [comment]
Nice. Thanks.
