### ISSUE TITLE
[FEATURE] I want to add opencv layer in python3.12 AWS Lambda.

### ISSUE THREAD

**Issue by 78planet** [keithrozario/Klayers#434]
I want to add opencv layer in python3.12 AWS Lambda.

I'm searching here and there to add python3.12 opencv library in AWS Lambda.

Is there a python3.12 opencv library arn path in git here?

If not, is there a plan to add python3.12 opencv library arn in the future?

**Comment by keithrozario** [comment]
opencv is usually a difficult layer -- but you can try to create a pull requests, adding opencv to the config file.

If you would like a new package to be made a layer, raise a pull request modifying the pipeline/config/packages_p312.csv or pipeline/config/packages_p312-arm64.csv file (depending on which architecture you prefer).
