### ISSUE TITLE
Pytz layer permissions seem to be incorrect

### ISSUE THREAD

**Issue by ImperialXT** [keithrozario/Klayers#51]
It appears that there's an issue with the permissions on the pytz layer. 

I'm using Terraform to deploy functions and it appears to be attempting to get the layer versions by arn. This works fine on your boto3 layer but on the pytz layer it gets Access Denied.

I've tested in us-east-1, ap-southeast-1 and ap-southeast-2 and get identical results.

pytz:
Test Command:
`aws lambda get-layer-version-by-arn --arn arn:aws:lambda:ap-southeast-2:113088814899:layer:Klayers-python37-ptyz:1 --region ap-southeast-2`
Result:
Access denied

boto3:
Test Command:
`aws lambda get-layer-version-by-arn --arn arn:aws:lambda:ap-southeast-2:113088814899:layer:Klayers-python37-boto3:2 --region ap-southeast-2`
Result:
Success

**Comment by keithrozario** [comment]
Thanks. Indeed there was a permission issue, but I'm not sure what caused it. The permissions were correct as far as I could tell -- but I added new permissions and they seem to work now. Can you test and let me know?

**Comment by ImperialXT** [comment]
Still getting access denied. Are you testing from within the same account as the layers?

**Comment by keithrozario** [comment]
yes, used a different account. Can you try again -- it should work.

if it still doesn't -- I'll add new versions and see if that clears things up.

**Comment by ImperialXT** [comment]
Still no go... Tried from a few different accounts.

**Comment by keithrozario** [comment]
I'm still perplexed over what is wrong....
Please try version 2, I tested it via console and it works.
arn:aws:lambda:<region>:113088814899:layer:Klayers-python37-pytz:**2**

**Comment by ImperialXT** [comment]
So I've just figured out the root cause now and I'm rather embarrassed to admit it was PEBKAC.

It appears I managed to typo "pytz" as "ptyz" on multiple occasions including in my initial issue posting here...

Sorry about wasting your time here.

**Comment by keithrozario** [comment]
Haha. No worries.

At least I learnt two things, AWS provides a `no permission` error even if the layer doesn't exists, and what PEBKAC means :)
