### ISSUE TITLE
No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by tsuga** [keithrozario/Klayers#62]
With `arn:aws:lambda:us-west-2:113088814899:layer:Klayers-python37-numpy:1`, I'm getting an error.

```
START RequestId: XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX Version: $LATEST
Unable to import module 'lambda_function': 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "/var/lang/bin/python3.6",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.0" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'


END RequestId: XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
REPORT RequestId: XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX	Duration: 0.38 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 51 MB	
```

The following code should reproduce the error.

```
import json
import numpy


def lambda_handler(event, context):
    # TODO implement
    return {
        'statusCode': 200,
        'body': json.dumps('Hello from Lambda!')
    }
```

**Comment by keithrozario** [comment]
Most probably an issue with my build rather than your code. Can you try running this in a python3.7 runtime — as i built it using that runtime.

**Comment by tsuga** [comment]
It works file in a python3.7 runtime!

**Comment by keithrozario** [comment]
I assume you mean it works **fine** ?

Haha.

Thanks for raising this — I’ll put a note on the README.MD to mention that numpy only works in python3.7. 

I think if you pip install with a version of python, you can only run that package on that python version. And unfortunately all packages are built with 3.7 — hence only 3.7 will be supported. 

I’ll leave this open for a few days, until I get around to adding that note.

**Comment by tsuga** [comment]
Sorry for the typo. It works **fine** with python 3.7!
Since numpy only works in python 3.7, pandas only works in python 3.7 as well.

It would be great i the layer package is built with 3.6.

**Comment by keithrozario** [comment]
I'm sorry man, but maintaining 2 separate layer versions will be pretty tough, and at the moment I haven't created the tooling to do that.

I've made a note that only Python3.7 runtime is supported -- hopefully you can use it.
