### ISSUE TITLE
Spacy Layer: Error while loading spacy.load("en")

### ISSUE THREAD

**Issue by biranchi2018** [keithrozario/Klayers#65]
I added the Spacy layer to my lambda function.
`- arn:aws:lambda:ap-southeast-1:113088814899:layer:Klayers-python37-spacy:2
`

It works fine when i import the spacy library
`import spacy
`
But i get errors while i try to load the "en" or "en_core_web_sm" packages.
```

nlp = spacy.load("en")
# nlp = spacy.load('en_core_web_sm')
# nlp = spacy.load('en_core_web_md')

```

Error while loading scpay packages:
```

{
    "errorMessage": "[E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.",
    "errorType": "OSError",
    "stackTrace": [
        "  File \"/var/lang/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n",
        "  File \"/var/lang/lib/python3.7/imp.py\", line 171, in load_source\n    module = _load(spec)\n",
        "  File \"<frozen importlib._bootstrap>\", line 696, in _load\n",
        "  File \"<frozen importlib._bootstrap>\", line 677, in _load_unlocked\n",
        "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
        "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
        "  File \"/var/task/handler.py\", line 30, in <module>\n    nlp = spacy.load(\"en\")\n",
        "  File \"/opt/python/spacy/__init__.py\", line 27, in load\n    return util.load_model(name, **overrides)\n",
        "  File \"/opt/python/spacy/util.py\", line 171, in load_model\n    raise IOError(Errors.E050.format(name=name))\n"
    ]
}

```

Please provide some working example.

Thanks
Biranchi

**Comment by keithrozario** [comment]
The model isn’t provided in the layer. As it’ll take up space, and I didn’t want to include it.

There’s two options, the best would be to download the model, zip it up into a layer and include that layer in your function. You can then load the model via `spacy.load(‘/opt/model_name’)` 

The other option, is download the model during function boot-up and load it.

Sorry it’s not in the layer :(

**Comment by dfuentes77** [comment]
I see the layer for the model `en_core_web_sm`:
```
arn:aws:lambda:us-west-2:770693421928:layer:Klayers-python38-spacy_model_en_small:1
```

Would be great to have a layer also for `en_core_web_md`.
