### ISSUE TITLE
tesseract:2 layer not found

### ISSUE THREAD

**Issue by technoir9** [keithrozario/Klayers#66]
I tried to include the tesseract:2 layer in one of my chalice apps and got such an error when I tried to deploy it:

```
An error occurred (AccessDeniedException) when calling the
 UpdateFunctionConfiguration operation: User:
 arn:aws:iam::my_aws_user is not authorized to perform:
 lambda:GetLayerVersion on resource: arn:aws:lambda:us-
 east-1:113088814899:layer:Klayers--tesseract:2
```

tesseract:1 layer works though.

**Comment by keithrozario** [comment]
Let me check this and get back to you.

**Comment by keithrozario** [comment]
Thanks for reaching out. My bad, the ARN given was in the wrong format :(.

I've corrected this in the README file, please let me know if you can access it. Please also note, depending on your user role and IAM permission for the CLI you may not be able to access the layer. Try attaching it to your lambda function either via GUI or CLI or using SLS framework.

`arn:aws:lambda:<region>:113088814899:layer:Klayers-python37-tesseract:1`

**Comment by technoir9** [comment]
Thanks for the response, works like a charm! On a side note, I had to set the `TESSDATA_PREFIX` env variable, plus the environment variable to the tesseract executable (didn't have to set those for the previous layer).

**Comment by keithrozario** [comment]
Hmmm, what were the values you had to set?

**Comment by technoir9** [comment]
`/opt/tesseract/tesseract/share/tessdata` and `/opt/tesseract/bin/tesseract`.
