### ISSUE TITLE
[FEATURE] How can I contribute? (adding a new package)

### ISSUE THREAD

**Issue by tsuga** [keithrozario/Klayers#71]
I'm thinking of contributing to this project by adding a new package (namely scikit-learn, pystan, etc.).

Which file(s) should I modify to add a new package as a new layer (via pull request)?

**Comment by keithrozario** [comment]
Please add to the serverless/config/<stage>/packages.csv file.

Appreciate if you would follow the format. Please add to both Klayers-Dev and Klayers-prod.

Also, if you could test this before making the pull requests that’ll be great.

Keith
