### ISSUE TITLE
[BUG] Layer does not exist

### ISSUE THREAD

**Issue by zachlevy** [keithrozario/Klayers#76]
**Describe the bug**
Trying to add a layer to a Lambda via AWS, I get Layer version does not exist
```
Layer version arn:aws:lambda:us-east-1:113088814899:layer:Klayers-python37-opencv-python-headless:5 does not exist.
```

**Screenshots**
![Screen Shot 2019-12-29 at 1 03 47 PM](https://user-images.githubusercontent.com/3211740/71560735-af420d00-2a3b-11ea-8413-a104d2bb2066.png)

**Layer Version ARN:**
I was previously using 
`arn:aws:lambda:us-east-1:113088814899:layer:Klayers-python37-opencv-python-headless:4` successfully.
Now for version 4 I get Layer version does not exist, so I tried upgrading to version 5, same problem.
`Layer version arn:aws:lambda:us-east-1:113088814899:layer:Klayers-python37-opencv-python-headless:5 does not exist.`

**Framework:**
None, adding layers via AWS Lambda GUI

**Comment by keithrozario** [comment]
Unfortunately to save space and limit the number of active versions I delete older layer versions 30 days after the underlying package upgrades to a new version.

Currently for opencv the version number for us-east-1 is 6&7 (use 7). You can view all active arns here:

https://github.com/keithrozario/Klayers/blob/master/deployments/python3.7/arns/us-east-1.json
