### ISSUE TITLE
[FEATURE]ReportLab-Integration

### ISSUE THREAD

**Issue by ChrisInspect** [keithrozario/Klayers#78]
**Is your feature request related to a problem? Please describe.**
I am reading that many people (including me) have problems to run ReportLab to create PDF's on AWSLambda. ReportLab interacts with Pillow and makes a lot of problems inside the Lambda-Environment

**Describe the solution you'd like**
Integration of the ReportLab-package

**Comment by keithrozario** [comment]
I can include a version of the package in the next iteration if you like.

Could you make a pull request? Modifying the `new_packages` branch. 

Please modify the following files:

- pipeline/serverless_python3.8/config/Klayers-defaultp38/packages.csv
- pipeline/serverless_python3.8/config/Klayers-prod38/packages.csv
- README.MD (adding your package to the list of Python Packages)

**Comment by keithrozario** [comment]
Just added this, it should get built by Monday next week. Stay tuned.

**Comment by keithrozario** [comment]
This has been added to python3.8 deployments.
