### ISSUE TITLE
[BUG] Unable to list-layer-versions against ARN

### ISSUE THREAD

**Issue by jdheyburn** [keithrozario/Klayers#81]
**Describe the bug**
Unable to list-layer-versions against layer arn `arn:aws:lambda:eu-west-1:113088814899:layer:Klayers-python37-requests`

**Screenshots**
```
aws --region eu-west-1 lambda list-layer-versions --layer-name arn:aws:lambda:eu-west-1:113088814899:layer:Klayers-python37-requests                          

An error occurred (AccessDeniedException) when calling the ListLayerVersions operation: User: REDACTED is not authorized to perform: lambda:ListLayerVersions on resource: arn:aws:lambda:eu-west-1:113088814899:layer:Klayers-python37-requests
```

**Layer Version ARN:**
arn:aws:lambda:eu-west-1:113088814899:layer:Klayers-python37-requests

**Framework:**
AWS CLI

**Additional context**
In order for our lambdas to pull the latest version of a layer, we list out all layer versions and retrieve the most recent one. We do this because we have no means of finding what is the latest one. This functionality was available in the past but looks like it is no longer available.

Appreciate the help on this.

**Comment by keithrozario** [comment]
Thanks. I need sometime to think about how I'm going to allow this. Can I understand what's your use-case? I'd be happier to provide this via a well structured API than a AWS call.

The issue is that while I've granted permissions for all IAM Principals (*) to download the layers, I've not granted the same permissions to the `list-layer-version` api call. Opening this up is possible, but again a public facing rest api is probably a better option than this for me.

In the mean-time I've accelerated some work on making the layer list a bit more human readable, I've swapped out the json list for csv, hopefully they're easier to digest:
https://github.com/keithrozario/Klayers/tree/master/deployments/python3.7/arns
https://github.com/keithrozario/Klayers/tree/master/deployments/python3.8/arns

**Comment by jdheyburn** [comment]
Our use case is we maintain a wrapper around AWS CLI for a suite of lambdas for our developers. They request to use the latest version available for a layer, to which an automated flow will query AWS via `list-layer-versions` in order to retrieve said version - before copying it to the destination account.

Without this we would have to perform a manual check on what the current layer version available is, but versions may expire over time.

I feel a public API is more complex than necessary. I understand you do not wish to grant more permissions than required. If that's the case we can come up with an alternative solution for ourselves.

Let me know if you'd like further info :)

**Comment by keithrozario** [comment]
Thanks. I currently can't find a way to let other accounts in AWS list layer versions in my account. Will take a look over the next few days.

**Comment by jdheyburn** [comment]
The functionality was there before. If you want to restrict it I believe you want this permission:
`lambda:ListLayerVersions`

From here: https://docs.aws.amazon.com/lambda/latest/dg/API_ListLayerVersions.html

Then you can apply it to the lambda resource, opening for all accounts
https://docs.aws.amazon.com/lambda/latest/dg/access-control-resource-based.html#permissions-resource-xaccountlayer

At least that's how I think you'd be able to do it 🙂

**Comment by keithrozario** [comment]
Hey @jdheyburn I tried this before but it won't work.

The `ListLayerVersions` permission can only be set at the layer level, and not at the layer_version level, currently there seems to be no way to modify these permissions to allow all Principals to add them :(

**Comment by jdheyburn** [comment]
Coming back to this - we've since worked around it by having users request a specified layer version, to which then our CI pipeline will copy that layer to our own account. So we can close this if necessary.

Out of curiosity, is setting `ListLayerVersions` a problem to have publicly exposed?

**Comment by keithrozario** [comment]
hey @jdheyburn, I forgot, but I think there is no way to publicly expose this to external accounts. Not without an `sts:AssumeRole` call or similar. An API would be a better option, I'm working on that -- but a bit slow, as I had to refactor the DynamoDB, fortunately that's complete the API shouldn't take too long.

**Comment by keithrozario** [comment]
API is finally done :)

https://api.klayers.cloud/api/v1/builds/latest
https://api.klayers.cloud/api/v1/layers/latest/{region}
https://api.klayers.cloud/api/v1/layers/latest/{region}/{package}
https://api.klayers.cloud/api/v1/layers/{region}/{package}

it's still in beta -- looking forward to feedback.

**Comment by keithrozario** [comment]
Finally get to close this. Let me know how the API goes, will be closing this long standing issue very soon :)

**Comment by jdheyburn** [comment]
Thanks - looks good!
