### ISSUE TITLE
[BUG] cannot import name '_imaging' from 'PIL'

### ISSUE THREAD

**Issue by nexeh** [keithrozario/Klayers#94]
**Describe the bug**

I cant seem to get away from this error message. I'm having this error on my own layers which was the reason i was trying yours but i see the same error message. Can you give me guidance on this. Im not sure if there is a layer issue or a gap in my understanding?

```
[ERROR] ImportError: cannot import name '_imaging' from 'PIL' (/var/task/PIL/__init__.py)
Traceback (most recent call last):
  File "/var/task/src/event-processing/process-fax.py", line 210, in ocr_handler
    from PIL import Image
  File "/var/task/PIL/Image.py", line 69, in <module>
    from . import _imaging as core
```

**Layer Version ARN:**
I have tried using `arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-Pillow:2` in combo with my code to get Pillow.

Then i tried to just use your tesseract layer to remove my layers from the picture. `arn:aws:lambda:us-east-1:113088814899:layer:Klayers-python37-tesseract:1` From the stack trace i can see that PIL is found so this feels like its a OS level issue which is seemingly what i have been chasing for some time now. I was hoping the use of the layer would fix that and was the intended purpose of the layer.

**Framework:**
Serverless

Help?

**Comment by nexeh** [comment]
I attempted top boil this issue down to as simple as i can

serverless.yml function definition
```
  testpillow:
    handler: src/event-processing/process-fax.pillow_handler
    runtime: python3.8
    layers:
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-Pillow:2
```

Handler
```
def pillow_handler(event, context):
    from PIL import Image
    print("Success!")
```

Same error:
```
START RequestId: 8665661c-48e5-493c-b44a-6157a9bb8c6f Version: $LATEST
[ERROR] ImportError: cannot import name '_imaging' from 'PIL' (/var/task/PIL/__init__.py)
Traceback (most recent call last):
  File "/var/task/src/event-processing/process-fax.py", line 239, in pillow_handler
    from PIL import Image
  File "/var/task/PIL/Image.py", line 69, in <module>
    from . import _imaging as coreEND RequestId: 8665661c-48e5-493c-b44a-6157a9bb8c6f
REPORT RequestId: 8665661c-48e5-493c-b44a-6157a9bb8c6f	Duration: 55.23 ms	Billed Duration: 100 ms	Memory Size: 1024 MB	Max Memory Used: 87 MB	Init Duration: 609.30 ms	

```

**Comment by nexeh** [comment]
I haven't finished connecting the dots here but i just got the above situation working by removing `pytesseract` from my requirement file. So that must mean they are conflicting in some way?

Next i removed the Pillow layer and added the tesseract layer(`arn:aws:lambda:us-east-1:113088814899:layer:Klayers-python37-tesseract:1`) and PIL is not included so i get an error as expected. this just confirmed that PIL/Pillow are not in included in this layer

I then added both layers and the error for PIL import goes away! WOOT! And for the record you can have the layers in any order.

Then when i get back to my original code i find that now i'm facing the error: `[ERROR] ModuleNotFoundError: No module named 'pytesseract'`. which makes sense becuase i removed it from my requirements to resolve the PIL issue.

So thats where i am, i dont think this is a issue in your layers. So i guess where i could use some help in my understanding would be whats included in the tesseract layer and how can i use it ? My current understanding is pytesseract is the python wrapper to do that.

**Comment by keithrozario** [comment]
You can see what’s in the Pytesseract layer from the repo here:

Klayers/deployments/python3.7/packages/pytesseract/requirements.txt

Which at least for now includes version 7.0.0 of the pillow.

I think if you overload them, it might conflict the two packages.

**Comment by nexeh** [comment]
Oh, that is helpful. i had not discovered that at this point but that makes total sense. I eliminated the Pillow layer all together. I am stuck on the error that tesseract is not installed. i tried just calling it manually as well and doesn't seem to be available on the path.

```
{
  "errorMessage": "tesseract is not installed or it's not in your path",
  "errorType": "TesseractNotFoundError",
  "stackTrace": [
    "  File \"/var/task/src/event-processing/process-fax.py\", line 79, in pillow_handler\n    print(str(((pytesseract.image_to_string(Image.open(local_file_name))))))\n",
    "  File \"/opt/python/pytesseract/pytesseract.py\", line 347, in image_to_string\n    }[output_type]()\n",
    "  File \"/opt/python/pytesseract/pytesseract.py\", line 346, in <lambda>\n    Output.STRING: lambda: run_and_get_output(*args),\n",
    "  File \"/opt/python/pytesseract/pytesseract.py\", line 257, in run_and_get_output\n    run_tesseract(**kwargs)\n",
    "  File \"/opt/python/pytesseract/pytesseract.py\", line 229, in run_tesseract\n    raise TesseractNotFoundError()\n"
  ]
}
```

**Comment by keithrozario** [comment]
Pytesseract doesn’t have the tesseract binary. You’ll need to pull in that layer as well.

**Comment by nexeh** [comment]
Yeah that is the error i get with the tesseract layer.

**Comment by keithrozario** [comment]
Can you share you code / repo?

**Comment by nexeh** [comment]
Yeah sure. Ill just boil it down so something simple to demonstrate. give me a little bit and ill send that over.

**Comment by keithrozario** [comment]
Haven't heard back in a while. Forgot to mention you need to set $PATH to the lambda layer as well. Hope you resolved your issue.

**Comment by TheLucasMoore** [comment]
I realize this has been closed a while... but is there a binary layer for tesseract for python 3.8?

I have this:
```
functions:
  my-function:
    layers:
      - arn:aws:lambda:us-west-1:770693421928:layer:Klayers-python38-pytesseract:14
```

And am getting this `"errorMessage": "tesseract is not installed or it's not in your PATH. See README file for more information."`

This convo above seems to imply I need something similar to `arn:aws:lambda:us-west-1:113088814899:layer:Klayers-python38-tesseract:1` in my layers, but I don't see anything listed in the [arns](https://github.com/keithrozario/Klayers/blob/master/deployments/python3.8/arns/us-west-1.csv) for tesseract or python 3.8

I'm happy to make another issue for this too.
