### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Rkauff** [keithrozario/Klayers#98]
Would it be possible to build a layer for Matplotlib as well? It would be great to have an ARN to use in Lambda.

**Comment by keithrozario** [comment]
Will look into this at the end of week. If it fits int a lambda shouldn't be too hard.

**Comment by keithrozario** [comment]
@Rkauff what's the use-case here. Have you found a way to visualize stuff off a lambda function?

I intentionally excluded all plotting/graphing/visual packages simply because I didn't think anyone had a use for them. Is there a way you hope to use matplotlib?

**Comment by Rkauff** [comment]
@keithrozario, Use case: I'm wanting to build a twitter bot that will plot (and tweet) the US Treasury Yield Curve.

**Comment by asbarakarimnurema** [comment]
Also interested here. I build a lambda function that plots a chart using panda and matplotlib.

**Comment by asbarakarimnurema** [comment]
**Detailed scenario**

1. Plot the chart
2. save locally
3. move to s3
4. send the bot message with the s3 image url

**Comment by Rkauff** [comment]
@asbarakarimnurema I don't believe you will be able to save locally from a Lambda function. Why not just skip step 2 and go straight from plotting to saving to S3?

**Comment by asbarakarimnurema** [comment]
You can save on `/tmp`, but going straight to S3 is also an option for sure

**Comment by keithrozario** [comment]
Looks like there’s demand for this, let me add it over the weekend.

**Comment by keithrozario** [comment]
Good news, `matplotlib` comes in at ~36MB, which means it can fit into a layer.

Layer will be published tomorrow, but for now. you can use the layer using the arn below:

`arn:aws:lambda:us-east-1:770693421928:layer:Klayers-python38-matplotlib:1`

Substitute us-east-1 with whatever region you're working from.

**Comment by Rkauff** [comment]
@keithrozario Awesome 👍 :)

**Comment by Rkauff** [comment]
@keithrozario,I just tested with a generic lambda that imports matplotlib and got a successful response. Nice one!

{
  "statusCode": 200,
  "body": "\"Hello from Lambda!\""
}

**Comment by keithrozario** [comment]
Can you let me know once you’ve done your project — be interested to see it.

**Comment by Rkauff** [comment]
Yep, will do!

**Comment by Rkauff** [comment]
@keithrozario, are you on twitter?

**Comment by keithrozario** [comment]
Yup. @keithrozario :)
