### ISSUE TITLE
[FEATURE] Creating new layers.

### ISSUE THREAD

**Issue by Olamyy** [keithrozario/Klayers#99]
**Is your feature request related to a problem? Please describe.**
Would be great if there was some documentation on how to contribute new layers.

**Describe the solution you'd like**
A documentation of how to navigate the project and or create new layers.

**Comment by keithrozario** [comment]
If you need to create layers -- make a pull request, changing the `pipeline/config/Klayers-prodp38` file.  Please ensure it follows the csv format (including the author and license type). :)
